### ISSUE TITLE
AFK integration

### ISSUE THREAD

**Issue by Turbotailz** [LuckPerms/ExtraContexts#9]
Would it be possible to add a context for whether the player is in AFK mode? I use Essentials but it could potentially hook into AFK for other plugins, too.

**Comment by lucko** [comment]
You can achieve this using PlaceholderAPI - `%essentials_afk%` is the placeholder you need.

so:

```yml
placeholderapi: true
placeholderapi-placeholders:
  afk: "%essentials_afk%"
```
